### ISSUE TITLE
Abstracción

### ISSUE THREAD

**Issue by DanBaDo** [LuisAguadoVicaria/react-star-wars-wiki#1]
Estupendo!

La cosa se pone interesante. Cuidado porque pisas una linea peligrosa: estás al borde de la [sobreingeniería](https://es.wikipedia.org/wiki/Sobreingenier%C3%ADa).

Al margen de eso, ya que aquí de lo que se trata es de aprender, te propongo dos formas de hacer esto y te menciono porqué hacerlo de otro modo. Los componentes/vistas que estás presentando son grandes. Tienen demasiada lógica en ellos. Se tienen que ocupar de muchas cosas. Eso va en cotra de dos cosas:

- La funcionalidad principal de los componentes debería de ser mostrar algo y capturar las interacciones con el usuario.
- Cada pieza de software ha de tener una única finalidad. Una única responsabilidad.

Atendiendo a lo anterior, las operaciones lógicas complejas que no estén relacionadas de con finalidades propias de un componente deberíamos de sacarlas del mismo.

Esta construcción que haces de enlaces y rutas en base a un array podemos sacarla de este componente de varias maneras:
- Escribiéndolas como funciones exportadas en un fichero .js a parte (librería), siempre que no necesitemos funcionalidades propias de React para ello, de otro modo no funcionarían pues React no gestionaría ese fichero.
- Escribiéndolas en un componente a parte que renderice los elementos que neceitamos (rutas, enlaces) para importar el componente y usar el este del que sacaríamos el código.
- Escribiéndolas como un hook de React personalizado, que es algo que te va a gustar.

Un hook personalizado es un componente de React que tiene un nombre que empieza por "use" y que no renderiza su return, sino que lo entrega como salida igual que una función normal. Podrías escribir un hook `useRoutes` que usarías de la siguiente manera en tu linea 20:
```js
const routes = useRoutes(pages)
```
Moviendo todo el código de la función, con las adaptaciones pertinentes, al hook personalizado.
Esto reduciría el tamaño del componente en 20 lineas, un 20%, delimitaría mejora las responsabilidades de cada componente y haría el código más flexible y fácil de mantener, pues podríamos usar estos hooks en el componente o vista que necesitásemos en cada momento sin necesidad de modificar su código.

https://github.com/LuisAguadoVicaria/react-sw-reading/blob/0aa65be8e91fb42bf167eb284eb56f63e8b7b918/src/App.js#L20-L45

**Comment by LuisAguadoVicaria** [comment]
e99a37efa691564951f26a6dc5eb857057a469cb
