### ISSUE TITLE
const y fichero de configuraciones

### ISSUE THREAD

**Issue by DanBaDo** [LuisAguadoVicaria/react-star-wars-wiki#2]
Esta linea pide a gritos cambiar el `let` por un `const`. No tiene mayor importancia, pero si no vamos a reasignar el valor siempre preferiremos el const.

Además y más importante, este tipo de definiciones de datos que no forman propiamente parte de la "actividad" del programa pero nos permiten personalizar su funcionamiento, deberíamos guardarlas todas juntas exportadas en un fichero con esa finalidad. ¿`config.js`?.

https://github.com/LuisAguadoVicaria/react-sw-reading/blob/0aa65be8e91fb42bf167eb284eb56f63e8b7b918/src/App.js#L13

**Comment by LuisAguadoVicaria** [comment]
e99a37efa691564951f26a6dc5eb857057a469cb
