### ISSUE TITLE
Vistas... componentes...

### ISSUE THREAD

**Issue by DanBaDo** [LuisAguadoVicaria/react-star-wars-wiki#4]
Dada la complejidad que añade a tu código el factory que incorporas (si no lo sabías [lo que estás haciendo tiene nombre](https://refactoring.guru/es/design-patterns/factory-method), y eso quiere decir que lo estás haciendo bien) y que hace que el código se aparte de lo "típico" o lo que se suele esperar, sería interesante reorganizar el código para que queden claras las finalidades de los diferentes ficheros.

- Los que renderizan un elemento en un contexto de la pantalla son "componentes" o "subcomponentes".
- Los que construyen la maquetación global de lo que se ve en la pantalla en un momento dado son "vistas".
- El que mantienen un contexto general que se mantiene para las diferentes vistas es el "layout".
- Los que no renderizan nada son "hooks".
- Los que agrupan funciones que se emplean en otros ficheros del programa son "librerias".
- Los que definen tipos de datos que se usan en diferentes partes de la aplicación son "defines".
- Los que almacenan parámetros que nos permiten personalizar el comportamiendo de la aplicación son "configuraciones".

Usar nombres de ficheros y carpetas que definan la naturaleza de cada cosa y cómo están relacionadas entre si ayuda a que el código sea más fácil de mantener en el futuro.

**Comment by LuisAguadoVicaria** [comment]
e99a37efa691564951f26a6dc5eb857057a469cb
